# Generated by Django 4.2.6 on 2023-11-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-creation_date',), 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
