# Generated by Django 4.2.6 on 2023-10-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_date_of_change_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category',), 'verbose_name': 'Приложение', 'verbose_name_plural': 'Приложения'},
        ),
    ]
