# Generated by Django 4.2.6 on 2023-11-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_change',
            field=models.DateField(auto_now_add=True, verbose_name='Дата последнего изменения'),
        ),
    ]
