# Generated by Django 4.2.6 on 2023-11-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category',), 'permissions': [('set_is_published', 'Can public for sale'), ('set_description', 'Can edit description'), ('set_category', 'Can change category')], 'verbose_name': 'Приложение', 'verbose_name_plural': 'Приложения'},
        ),
    ]
